export { default as LoginScreen } from './login/login.screen'
export { default as RegisterScreen } from './register/register.screen'
export { default as ProfileScreen } from './profile/profile.screen'
export { default as FavoritesScreen } from './myFavorites/favorites.screen'
export { default as MoviesScreen } from './movies/main.screen'
export { default as MovieScreen } from './movies/movie.screen'
export { default as TvShowsScreen } from './tvShows/main.screen'
export { default as TvShowScreen } from './tvShows/tvShow.screen'